language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
script: true
# whitelist
branches:
    only:
        - master
        - develop

after_success: 
    - coveralls
