"""empty message

Revision ID: 12272d5607ab
Revises: None
Create Date: 2014-03-28 23:10:43.386973

"""

# revision identifiers, used by Alembic.
revision = '12272d5607ab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('akaraisin_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'akaraisin_url')
    ### end Alembic commands ###
