"""empty message

Revision ID: 2dc8b46903e2
Revises: 12272d5607ab
Create Date: 2014-04-18 12:36:16.999270

"""

# revision identifiers, used by Alembic.
revision = '2dc8b46903e2'
down_revision = '12272d5607ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_page')
    ### end Alembic commands ###
