"""empty message

Revision ID: 39dbade2306
Revises: 41768f9a3408
Create Date: 2014-04-18 12:45:07.682414

"""

# revision identifiers, used by Alembic.
revision = '39dbade2306'
down_revision = '41768f9a3408'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
