"""empty message

Revision ID: 41768f9a3408
Revises: 261b49b2568c
Create Date: 2014-04-18 12:43:11.424039

"""

# revision identifiers, used by Alembic.
revision = '41768f9a3408'
down_revision = '261b49b2568c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_page', sa.Column('QuestionContent', sa.String(length=120), nullable=True))
    op.add_column('about_page', sa.Column('QuestionTitle', sa.String(length=80), nullable=True))
    op.add_column('about_page', sa.Column('bigTitle', sa.String(length=80), nullable=True))
    op.add_column('about_page', sa.Column('hditwTitle', sa.String(length=80), nullable=True))
    op.add_column('about_page', sa.Column('hdiwContent', sa.String(length=120), nullable=True))
    op.add_column('about_page', sa.Column('missionContent', sa.String(length=120), nullable=True))
    op.add_column('about_page', sa.Column('missionTitle', sa.String(length=80), nullable=True))
    op.drop_column('about_page', 'bigTitleContent')
    op.drop_column('about_page', 'otherQuestionTitle')
    op.drop_column('about_page', 'howDoesItWorkContent')
    op.drop_column('about_page', 'otherQuestionContent')
    op.drop_column('about_page', 'ourMissionContent')
    op.drop_column('about_page', 'howDoesItWorkTitle')
    op.drop_column('about_page', 'ourMissionTitle')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_page', sa.Column('ourMissionTitle', sa.VARCHAR(length=80), nullable=True))
    op.add_column('about_page', sa.Column('howDoesItWorkTitle', sa.VARCHAR(length=80), nullable=True))
    op.add_column('about_page', sa.Column('ourMissionContent', sa.VARCHAR(length=120), nullable=True))
    op.add_column('about_page', sa.Column('otherQuestionContent', sa.VARCHAR(length=120), nullable=True))
    op.add_column('about_page', sa.Column('howDoesItWorkContent', sa.VARCHAR(length=120), nullable=True))
    op.add_column('about_page', sa.Column('otherQuestionTitle', sa.VARCHAR(length=80), nullable=True))
    op.add_column('about_page', sa.Column('bigTitleContent', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('about_page', 'missionTitle')
    op.drop_column('about_page', 'missionContent')
    op.drop_column('about_page', 'hdiwContent')
    op.drop_column('about_page', 'hditwTitle')
    op.drop_column('about_page', 'bigTitle')
    op.drop_column('about_page', 'QuestionTitle')
    op.drop_column('about_page', 'QuestionContent')
    ### end Alembic commands ###
